### ISSUE TITLE
RIPTiDe fundamentals

### ISSUE THREAD

**Issue by poeplau** [bbfrederick/rapidtide#105]
Hello
I'm a Masters student working on physiological noise correction in resting state fmri.
I have a question regarding the fundamentals: according to the documentation rapidtide performs the RIPTiDe algorithm which in turn according to your publications (e. g. doi.org/10.3389/fnins.2019.00787 and https://doi.org/10.1016/j.neuroimage.2011.03.071) performs multiple GLM analyses one for each shifted regressor.
By my understanding this is not what rapidtide does, so my question is whether rapidtide is the improved version of the original RIPTiDe approach or whether they are separate.
Thank you!

**Comment by poeplau** [comment]
Thank you so much for the detailed answer! Might I ask for your help with another problem?
The --preservefiltering argument doesn't work properly for me. A few outputs are empty, e. g.  the R/R2 maps or the cleaned BOLD map, when I use this option.
May I also ask usage questions using this thread? (I realize there is a neurostars links for that, but it semmed pretty dead to me)

**Comment by bbfrederick** [comment]
Sure - I'm hardly formal about things.  But if you have multiple, distinct bugs after this one, it would be good to open separate issues going forward.  I think that's the way real software projects are supposed to work.

Re: --preservefilitering.  This is a very weird bug.  First off, looking at the code, I have no idea why it ever worked, which is a little disturbing :-) (and it did used to work, because I put the feature in for a specific purpose, and it served my needs at the time).  More to the point, there is a clear way to fix it, but implementing that causes the GLM filtering to just hang, and I have no idea why.  Some weird interaction between shared memory, multiprocessing, and avant-garde array views, I guess, but at the moment I'm stumped.  I'll look at it more later today.

**Comment by poeplau** [comment]
Okay, thank you. I'll open new issues regarding usage or other questions going forward. :)
