### ISSUE TITLE
Not able to generate desc-shiftedtcs_bold NIFTI using documentation instructions

### ISSUE THREAD

**Issue by nnmenon** [bbfrederick/rapidtide#156]
I'm trying to generate the shiftedtcs_bold output as described in the documentation, but it's not being produced. Not sure what else to try to get the file. 

I'm running rapidtide with the --delaymapping flag and --nolimitoutput flag, and there's more than one pass for my data. I've read through almost all the documentation and haven't found anyone else with this issue, so not sure if there might be something for me to check in the installation of the rapidtide package. Any help is very appreciated.

**Comment by bbfrederick** [comment]
That's definitely a bug.  What version of rapidtide are you using?  I just recently revamped how you select which time courses to output, and it's possible in the leadup to that I broke something.

I just pushed a release that implements the new output strategy - v2.8.9 (there are some documentation changes that are going to take a while to resolve - I'll fix those in v2.8.9.1 so you can get this sooner rather than later).  The "shiftedtcs_bold" time courses will be written if you a) do the GLM (i.e. don't disable it with ``--noglm``, and you set ``--outputlevel`` to ``more`` or ``max``.  Alternately, if you continue to use ``--nolimitoutput``, which is now deprecated, it will set just set the output level to max.

Let me know if that fixes your problem.

**Comment by bbfrederick** [comment]
Well that was infuriating.  I misread a long chain of indents - it turns out you would only get shiftedtcs if: 1) passes > 1,  2) outputlevel is set to max (or nolimitoutput was set), AND you were running a GLM to denoise the data (that was not intended to be part of the selection logic).  This is fixed in 2.8.9.1.

**Comment by nnmenon** [comment]
Problem fixed! I was using 2.8.9 but I updated it and the file is generated now. Thank you for your help!
