### ISSUE TITLE
[DOC] Acquisition parameters that influence rapidtide?

### ISSUE THREAD

**Issue by dangom** [bbfrederick/rapidtide#21]
Dear Blaise,

Thanks for sharing your package.
I would like to used rapidtide2 to estimate blood arrival times in the visual cortex. I have a 7T task dataset with relatively high temporal (0.7s) and spatial (0.8mm iso) resolution, but with limited FOV (15 coronal slices covering 12mm). For preprocessing I've only motion corrected the data. Running `rapidtide2 in out` on my dataset worked, but results look very much like random noise.

I take from the documentation in the repository that rapidtide doesn't care whether we're dealing with task or resting datasets:

> The expectation is that rapidtide will be run as the last preprocessing step before resting state or task based analysis.

But I wonder what the optimal preprocessing would be, and whether there is an optimal set of acquisition parameters that I should use to improve the estimation. Perhaps an additional resting-state scan with a larger brain coverage would be more appropriate, or even collecting an external regressor?

I couldn't find pointers to issues with acquisition parameters in the documentation. Any pointers would be welcome.

**Comment by bbfrederick** [comment]
Hi Daniel,

Cool application!

There is sometimes a little bit of a learning curve dialing in settings for a new application, and that sounds sufficiently different from anything I've done so far that the defaults probably aren't appropriate.  A couple thoughts:
1)  As you suspect, motion correction is a very good idea.
2) You should do slice time correction, otherwise you're going to see stripes in the slice select direction.  While these carry information (like, whether you have your slice order right!), it's not interesting to your application.
3) I typically do some spatial filtering (in rapidtide).  For whole head high res multi band fMRI, I usually use 1.5-2mm of smoothing (-f 1.5 to -f 2).  I don't know what would be best for your data - maybe start with -f 0.5?

The most important issue, especially for tissue like the eyes, which are surrounded
