### ISSUE TITLE
Unexpected behaviors of showxcorr

### ISSUE THREAD

**Issue by antotorov** [bbfrederick/rapidtide#24]
Hello,

I am running showxcorr and found several weird behaviors.

The two time series are depicted in the attached figure:
![sampledata](https://user-images.githubusercontent.com/53940822/68215576-c508f800-ffdf-11e9-8863-023e366a955a.png)

The units of the y-axis are arbitrary and on the x-axis it are seconds.

I then run

`showxcorr file1 file2 samplingfreq1 -T`

Side note: the data I have don't have the same sampling frequency so I am using the -T option.

First question: when using the -T option, should the samplingfrequency argument correspond to the sampling frequency of the first or the second time course? (from experience it seems to be for the first but I'd like to make sure).

The resulting plot is

![crosscorr](https://user-images.githubusercontent.com/53940822/68215907-57a99700-ffe0-11e9-9919-ed66db1da0a5.png)

The stdout is
```
trimming data to match
executing findmaxlag
47 0.0 0.0 0.0 0 64
Pearson_R:	 -0.37657307486832087

Crosscorrelation_Rmax:	 0.283692827639751
Crosscorrelation_maxdelay:	 0.0
```
While the `Crosscorrelation_Rmax` seems to be correct, the `Crosscorrelation_maxdelay` seems completely off: by zooming a bit on the graph I find `x=-0.72` close to the maximum.
First thought: the range for the max search is too narrow (although that's inconsistent with the correct value of Crosscorrelation_Rmax...). But if the x-axis in the plot produced by showxcorr has units of seconds, then the default value of +/-15s should be fine... to make sure I used a huge range (using `-r 10000`) and it didn't change anything.

What am I missing here?

While playing around with the options, I tried showing the one-line summary:

`showxcorr file1 file2 samplingfreq1 -TaA`

and the stdout contains

```
pearson_r	pearson_p	xcorr_R	xcorr_t	xcorr_maxdelay
-0.37657307486832087 	 2.2441268669472504e-05 	 0.283692827639751 	 -0.0
```

Here I am a bit confused since the header line contain `xcorr_t` which doesn't seem to be assigned any value on the second line (it is also absent from the stdout in non-summry mode). By the way, what is supposed to be `xcorr_t`?

At this stage I thought maybe there is a floating point number issue, so I artificially decreased the samplingfrequency argument (say I went from 100Hz to 10Hz):

`showxcorr file1 file2 new_samplingfreq1 -T`

Now stdout contains

```
executing findmaxlag
5 8.651000654500356 0.20904401993193708 1.1916665055228675 1 0
Pearson_R:	 -0.37657307486832087

Crosscorrelation_Rmax:	 0.2100820076953138
Crosscorrelation_maxdelay:	 8.651000654500356
```

and the plot is essentially the same as above but with the x-values multiplied by 10, as it should.
The coordinates of this max is not the global max on the range of the plot. Running now 

`showxcorr file1 file2 new_samplingfreq1 -T -r 100`

now gives

```
trimming data to match
peak search restricted to +/- 100.0  seconds
executing findmaxlag
47 -7.238036259049293 0.2766952051810694 0.8854404080858456 1 0
Pearson_R:	 -0.37657307486832087

Crosscorrelation_Rmax:	 0.283692827639751
Crosscorrelation_maxdelay:	 -7.238036259049293
```
This is the expected behavior, although this Crosscorrelation_maxdelay: = -7.238... should have been spotted when running with the default +/-15s range parameter...

Finally, turning the summary mode on,

`showxcorr file1 file2 new_samplingfreq1 -TaA -r 100`

gives

```
trimming data to match
turning on label line
executing findmaxlag
47 -7.238036259049293 0.2766952051810694 0.8854404080858456 1 0
pearson_r	pearson_p	xcorr_R	xcorr_t	xcorr_maxdelay
-0.37657307486832087 	 2.2441268669472504e-05 	 0.283692827639751 	 7.238036259049293
```
so the sign of xcorr_maxdelay is wrong!!!!

To ease the discussion let me recap the questions/issues:

1. When using the -T option, to which timecourse should the sampling frequency correspond to?
2. Why is the default range parameter of +/-15s not detecting the max at about x=-0.72
3. When using -aA option, what is xcorr_t referring to? Why is it missing in the value line?
4. Decreasing the sampling frequency from 100 to 10 detects the local max at about x=8.5 but not the global max at x=-7.2. This is not what is expected, is it? Increasing the range to 100 allow the program to detect this global max.
5. The sign of xcorr_maxdelay is flipped when turning the using -aA, which is probably a bug.

Hope all this make sense !

Thanks for your help

**Comment by bbfrederick** [comment]
Hi - 

So sorry - I don't know why I didn't see this when you posted it...

I think I see the problem - showxcorr assumes the sample rate of the two signals are the same.  What the -T option does is: when there are two signals of the same sample rate, if they are different lengths, it truncates the longer one to the length of the shorter one.  So if I understand what you're trying to do, that is really NOT what you want.

As a longterm solution, it would be best if you could specify the sample rate of signal 1 and 2 separately; that's a good option, and I'll see about adding it.

There's a workaround for the time being, however.  There is another program in rapidtide, resamp1tc, that will resample a signal to anything you want.  So the procedure would be:

Assume signal 1 has sample rate Fs1, and signal 2 has sample rate Fs2.  If Fs1 > Fs2, upsample signal 2 to match it:
resamp1tc signal2 Fs2 signal2_resampled Fs1 --nodisplay

THEN you can run showxcorr:

showxcorr signal1 signal2_resampled Fs1 -T -w -t

This will do what I think you are trying to do.

By way of explanation:
I've included -T because even if signal1 and signal2 have the same extent in time, when you resample to the same sample rate often the lengths will be off by a point or two.  This fixes that.
I suggest always using -w and -t.  This gets rid of the effects of drift an end transients.  It tends to make the crosscorrelation much cleaner.  Try it with and without these two and see if it matters for your data.

Finally, since I think you're probably trying to find the correlation of the low frequency signal, you might want to play with the -F option to band limit the signals to low frequency.

**Comment by antotorov** [comment]
Thanks a lot for taking time to write this answer!
Shame on me, I completely misunderstood the -T option, it seems... since rapidtide2 can accommodate a regressor-specific sampling frequency using --regressorfreq I kind of though this was also possible in showxcorr.
So I'll try the things you propose and I am sure it'll work :-)
